### ISSUE TITLE
`alchemy`: `create` broken on main

### ISSUE THREAD

**Issue by JenkeScheen** [asapdiscovery/asapdiscovery#1062]
currently this happens: 
```
$ asap-alchemy create factory.json
Traceback (most recent call last):
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/bin/asap-alchemy", line 8, in <module>
    sys.exit(alchemy())
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1078, in main
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 783, in invoke
  File "/Users/jenkescheen/asapdiscovery/asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py", line 36, in create
    from asapdiscovery.alchemy.schema.fec import FreeEnergyCalculationFactory
  File "/Users/jenkescheen/asapdiscovery/asapdiscovery-alchemy/asapdiscovery/alchemy/schema/fec.py", line 6, in <module>
    import openfe
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openfe/__init__.py", line 22, in <module>
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openfe/setup/__init__.py", line 13, in <module>
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openfe/setup/alchemical_network_planner/__init__.py", line 4, in <module>
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openfe/setup/alchemical_network_planner/relative_alchemical_network_planner.py", line 35, in <module>
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openfe/protocols/openmm_rfe/__init__.py", line 4, in <module>
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openfe/protocols/openmm_rfe/_rfe_utils/__init__.py", line 1, in <module>
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openfe/protocols/openmm_rfe/_rfe_utils/lambdaprotocol.py", line 8, in <module>
    from openmmtools.alchemy import AlchemicalState
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openmmtools/__init__.py", line 8, in <module>
    from openmmtools import testsystems, integrators, alchemy, mcmc, states, cache, utils, constants, forces, forcefactories, storage, multistate
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openmmtools/multistate/__init__.py", line 64, in <module>
    from openmmtools.multistate.multistatesampler import MultiStateSampler
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openmmtools/multistate/multistatesampler.py", line 50, in <module>
    from openmmtools.multistate.utils import SimulationNaNError
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openmmtools/multistate/utils.py", line 32, in <module>
    from openmmtools.multistate.pymbar import subsample_correlated_data, statistical_inefficiency
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/openmmtools/multistate/pymbar.py", line 7, in <module>
    from pymbar.timeseries import (
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/pymbar/__init__.py", line 31, in <module>
    from pymbar import timeseries, testsystems, confidenceintervals, version
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/pymbar/confidenceintervals.py", line 25, in <module>
    import scipy.stats
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/scipy/stats/__init__.py", line 612, in <module>
    from ._binned_statistic import *
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/scipy/stats/_binned_statistic.py'
```

which is with `scipy  1.13.0   py310hdfaad59_0  conda-forge`

**Comment by JenkeScheen** [comment]
should probably test for this as well

**Comment by JenkeScheen** [comment]
upgrading scipy to 1.13.1 solved the issue

**Comment by ijpulidos** [comment]
This is curious since I see the file in 1.13.0, for example https://github.com/scipy/scipy/blob/v1.13.0/scipy/stats/_binned_statistic.py . But the issue might be specific to scipy on Apple/Silicon, though.

**Comment by JenkeScheen** [comment]
@ijpulidos yep looks like it. I'll leave it to @jthorton to decide whether to pin this or not.

**Comment by jthorton** [comment]
It looks like the last [CI which worked ](https://github.com/asapdiscovery/asapdiscovery/actions/runs/9278108197/job/25528562836#step:5:631) is using 1.13.1 so lets pin to that!
