### ISSUE TITLE
`alchemiscale.interface.client.AlchemiscaleClientError` on `asap-alchemy prioritize -nk <> -w 0.001`

### ISSUE THREAD

**Issue by JenkeScheen** [asapdiscovery/asapdiscovery#1256]
getting an internal error from Alchemiscale, looks like it's independent of `nk` or `weight`:
```
Traceback (most recent call last):
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/bin/asap-alchemy", line 8, in <module>
    sys.exit(alchemy())
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jenkescheen/asapdiscovery/asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py", line 733, in prioritize
    new_weight, old_weight = client.adjust_weight(
  File "/Users/jenkescheen/asapdiscovery/asapdiscovery-alchemy/asapdiscovery/alchemy/utils.py", line 373, in adjust_weight
    old_weight = self._client.get_network_weight(network=network_key)
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/interface/client.py", line 344, in get_network_weight
    return self._get_resource(f"/networks/{network}/weight")
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/base/client.py", line 144, in _wrapper
    return f(self, *args, **kwargs)
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/base/client.py", line 238, in _wrapper
    return f(self, *args, **kwargs)
  File "/Users/jenkescheen/micromamba/envs/asapdiscovery/lib/python3.10/site-packages/alchemiscale/base/client.py", line 366, in _get_resource
    raise self._exception(
alchemiscale.interface.client.AlchemiscaleClientError: Status Code 500 : Internal Server Error : Internal Server Error
```

**Comment by JenkeScheen** [comment]
this seems to have been a temporary behaviour, not happening anymore. @dotsdl feel free to close this issue unless you want to investigate more.

**Comment by dotsdl** [comment]
Thanks for this @JenkeScheen!

Odd...unclear to me what could have been happening from the traceback alone. Closing for now unless it rears its head again.
