### ISSUE TITLE
Prep failure is causing docking workflow failure

### ISSUE THREAD

**Issue by apayne97** [asapdiscovery/asapdiscovery#695]
From the log file:
```
2023-12-13 12:31:55,112 | root | INFO | cross_docking.py | cross_docking_workflow | Loaded 1 query ligands
2023-12-13 12:31:55,115 | root | INFO | cross_docking.py | cross_docking_workflow | Loaded 219 complexes
2023-12-13 12:31:55,117 | root | INFO | cross_docking.py | cross_docking_workflow | Prepping complexes
2023-12-13 12:31:57,084 | asapdiscovery.modeling.protein_prep_v2 | INFO | protein_prep_v2.py | prep | Loaded 218 cached structures from: /lila/data/chodera/asap-datasets/full_frag_prepped_mpro_20230122/du_cache_p_only.
2023-12-13 12:32:00,604 | asapdiscovery.modeling.protein_prep_v2 | INFO | protein_prep_v2.py | prep | Matched 216 cached structures which will be reused.
2023-12-13 12:32:00,607 | asapdiscovery.modeling.protein_prep_v2 | INFO | protein_prep_v2.py | prep | Prepping 3 complexes
```

From the error file. I've seen the `Warning: After setting primary alternate location, ' OXT ILE 43   B 0  ' and ' N   CYS 44   B 0  ' are too close 0.43 < 0.7A. This suggests unconventional altloc use, which is invalid using the 'Primary' OEAlternateLocationOption. Try again with the 'Enumerate' option.
Warning: No ligand or sites detected, please revise inputs and/or options` before but in the current workflow this just causes the whole thing to die. I could just catch the error in the workflow.
```
Warning: No BioAssembly transforms found, using input molecule as biounit: DesignUnit Components_LIG
Warning: Iridium - Structure: DesignUnit Components_LIG has no REMARK data
Warning: After setting primary alternate location, ' OXT ILE 43   B 0  ' and ' N   CYS 44   B 0  ' are too close 0.43 < 0.7A. This suggests unconventional altloc use, which is invalid using the 'Primary' OEAlternateLocationOption. Try again with the 'Enumerate' option.
Warning: No ligand or sites detected, please revise inputs and/or options
Traceback (most recent call last):
  File "/home/paynea/miniforge3/envs/asapdiscovery/bin/asap-docking", line 8, in <module>
    sys.exit(docking())
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/asapdiscovery/docking/cli.py", line 235, in cross_docking
    cross_docking_workflow(inputs)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/asapdiscovery/docking/workflows/cross_docking.py", line 167, in cross_docking_workflow
    prepped_complexes = prepper.prep(
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/asapdiscovery/modeling/protein_prep_v2.py", line 145, in prep
    outputs = self._prep(inputs=inputs)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/asapdiscovery/modeling/protein_prep_v2.py", line 298, in _prep
    raise ValueError("Failed to make design unit.")
ValueError: Failed to make design unit.
```

**Comment by apayne97** [comment]
Short term solution is to make it possible to ignore if failed

**Comment by hmacdope** [comment]
Ah ok if you are using dask, this will be ignored, but yes good idea to add a flag to ignore if running outside of dask environment. 

#679 doesn't actually fix this problem right? It kind of attacks it in a different way if that makes sense.  Something like https://github.com/choderalab/asapdiscovery/blob/fb6251a5b1b741515d7f156a8c89b024351577e3/asapdiscovery-docking/asapdiscovery/docking/openeye.py#L238-L245 is probably a solution we want to explore. 

Not to say that #679 isn't a useful addition in and of itself.

**Comment by hmacdope** [comment]
Fixed
