### ISSUE TITLE
`asap-docking`: cached directory fails when using `pdb-file`

### ISSUE THREAD

**Issue by apayne97** [asapdiscovery/asapdiscovery#960]
This might be true for a few different examples, but if I try:
```
asap-docking cross-docking --ligands input/lig_0.smi --pdb-file input/NP_722463.1_lig_0.pdb --target ZIKV-NS2B-NS3pro --cache-dir prep_cache_v2 --structure-selector PairwiseSelector --output-dir dock_output
```
It works, and I get this log output:
```
[04/08/24 12:16:48] INFO     Writing to / overwriting output directory:                                   cross_docking.py:101
                             /Users/alexpayne/Scientific_Projects/mers-drug-discovery/20240408-siyang-hel
                             p/dock_output
                    INFO     Running cross docking with inputs:                                           cross_docking.py:105
                             ligands='/Users/alexpayne/Scientific_Projects/mers-drug-discovery/20240408-s
                             iyang-help/input/lig_0.smi'
                             pdb_file=PosixPath('/Users/alexpayne/Scientific_Projects/mers-drug-discovery
                             /20240408-siyang-help/input/NP_722463.1_lig_0.pdb') fragalysis_dir=None
                             structure_dir=None
                             cache_dir='/Users/alexpayne/Scientific_Projects/mers-drug-discovery/20240408
                             -siyang-help/prep_cache_v2' use_only_cache=False save_to_cache=True
                             target=<TargetTags.ZIKV-NS2B-NS3pro: 'ZIKV-NS2B-NS3pro'>
                             write_final_sdf=True use_dask=False dask_type=<DaskType.LOCAL: 'local'>
                             dask_failure_mode=<DaskFailureMode.SKIP: 'skip'> dask_cluster_n_workers=10
                             dask_cluster_max_workers=200 n_select=5 logname='' loglevel='INFO'
                             output_dir=PosixPath('/Users/alexpayne/Scientific_Projects/mers-drug-discove
                             ry/20240408-siyang-help/dock_output') overwrite=True walltime='72h'
                             structure_selector=<StructureSelector.PAIRWISE: 'PairwiseSelector'>
                             multi_reference=False relax=<POSIT_RELAX_MODE.NONE: 0>
                             posit_method=<POSIT_METHOD.ALL: 15> use_omega=False omega_dense=False
                             num_poses=1 allow_low_posit_prob=False low_posit_prob_thresh=0.1
                             allow_final_clash=False allow_retries=False
                    INFO     Dumping input schema to                                                      cross_docking.py:106
                             /Users/alexpayne/Scientific_Projects/mers-drug-discovery/20240408-siyang-hel
                             p/dock_output/inputs.json
                    INFO     Loading ligands from file:                                                   cross_docking.py:126
                             /Users/alexpayne/Scientific_Projects/mers-drug-discovery/20240408-siyang-hel
                             p/input/lig_0.smi
                    INFO     Loading structures from pdb:                                         meta_structure_factory.py:79
                             /Users/alexpayne/Scientific_Projects/mers-drug-discovery/20240408-si
                             yang-help/input/NP_722463.1_lig_0.pdb
                    INFO     Loaded 1 query ligands                                                       cross_docking.py:142
                    INFO     Loaded 1 complexes                                                           cross_docking.py:144
                    INFO     Prepping complexes                                                           cross_docking.py:147
                    INFO     Prepping 1 complexes                                                          protein_prep.py:145
Warning: Detected residue with blank chain ID LIG 151     0
Warning: No BioAssembly transforms found, using input molecule as biounit: _lig_0_LIG
Warning: Iridium - Structure: _lig_0_LIG has no REMARK data
Processing BU # 1 with title: _lig_0_LIG, chains A
[04/08/24 12:17:24] INFO     Prepped 1 complexes                                                          cross_docking.py:160
                    INFO     Writing prepped complexes to global cache                                    cross_docking.py:163
                             /Users/alexpayne/Scientific_Projects/mers-drug-discovery/20240408-siyang-hel
                             p/prep_cache_v2
                    INFO     Selecting pairs for docking                                                  cross_docking.py:169
                    INFO     Selected 1 pairs for docking                                                 cross_docking.py:178
                    INFO     Running docking on selected pairs                                            cross_docking.py:191
[04/08/24 12:17:31] INFO     Docked 1 pairs successfully                                                  cross_docking.py:212
                    INFO     Scoring docking results                                                      cross_docking.py:221
                    INFO     Writing final docked poses to SDF file                                       cross_docking.py:225
[04/08/24 12:17:32] INFO     Renaming columns for manifold
```

If I then run the same command with `--use-only-cache`, it fails:
```
asap-docking cross-docking --ligands input/lig_0.smi --pdb-file input/NP_722463.1_lig_0.pdb --target ZIKV-NS2B-NS3pro --cache-dir prep_cache_v2 --structure-selector PairwiseSelector --output-dir dock_output --use-only-cache
```

I get this log output
```
...
                    INFO     Loading structures from pdb:                                         meta_structure_factory.py:79
                                                 /Users/alexpayne/Scientific_Projects/mers-drug-discovery/20240408-si
                                                 yang-help/input/NP_722463.1_lig_0.pdb
                    INFO     Loaded 1 query ligands                                                       cross_docking.py:142
                    INFO     Loaded 1 complexes                                                           cross_docking.py:144
                    INFO     Prepping complexes                                                           cross_docking.py:147
                    INFO     Loaded 1 cached structures from:                                              protein_prep.py:123
                             /Users/alexpayne/Scientific_Projects/mers-drug-discovery/20240408-siyang-help
                             /prep_cache_v2.
                    WARNING  Disregarding 1 structures which could not be found in the cache.              protein_prep.py:132
Traceback (most recent call last):
  File "/Users/alexpayne/miniforge-pypy3/envs/asapdiscovery/bin/asap-docking", line 8, in <module>
    sys.exit(docking())
  File "/Users/alexpayne/miniforge-pypy3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/alexpayne/miniforge-pypy3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/alexpayne/miniforge-pypy3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/alexpayne/miniforge-pypy3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/alexpayne/miniforge-pypy3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/alexpayne/Scientific_Projects/asapdiscovery/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cli.py", line 266, in cross_docking
    cross_docking_workflow(inputs)
  File "/Users/alexpayne/Scientific_Projects/asapdiscovery/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cross_docking.py", line 149, in cross_docking_workflow
    prepped_complexes = prepper.prep(
  File "/Users/alexpayne/Scientific_Projects/asapdiscovery/asapdiscovery-modeling/asapdiscovery/modeling/protein_prep.py", line 163, in prep
    raise ValueError(
ValueError: No complexes were successfully prepped, likely that nothing was passed in, cache was mis-specified or cache was empty.
```

If this is really not working, then I think we need to add this as a test.

**Comment by hmacdope** [comment]
Is that PDB in the cache?

**Comment by hmacdope** [comment]
We don't currently support caching with `--pdb-file`, but you are right that this should be more explicit and fail if `--use-only-cache && --pdb-file`. It doesn't take long to prep a structure so should just be okay to not support for now.

**Comment by apayne97** [comment]
> Is that PDB in the cache?
it should be getting written to a cache from the first command:

> INFO     Writing prepped complexes to global cache                                    cross_docking.py:163
                             /Users/alexpayne/Scientific_Projects/mers-drug-discovery/20240408-siyang-hel
                             p/prep_cache_v2

> It doesn't take long to prep a structure so should just be okay to not support for now.
but if you have a large structure directory, but you just want to dock to one of the structures, and you have already prepped all of them, I think the natural thing would be to assume you could just specify one of the pdb files and have it confirm that its in the cache
