### ISSUE TITLE
dask errors, please help

### ISSUE THREAD

**Issue by apayne97** [asapdiscovery/asapdiscovery#965]
working in `asap-datasets/retro_docking/sars_fragalysis_retrospective/20240403_multi_pose_docking_self_docking`

```
2024-04-10 10:52:37,554 | root | INFO | cross_docking.py | cross_docking_workflow | Writing to / overwriting output directory: /lila/data/chodera/asap-datasets/retro_docking/sars_fragalysis_retrospective/20240403_multi_pose_docking_self_docking
2024-04-10 10:52:37,569 | root | INFO | cross_docking.py | cross_docking_workflow | Running cross docking with inputs: ligands='/lila/data/chodera/asap-datasets/mpro_fragalysis-04-01-24_curated_cache/combined.sdf' pdb_file=None fragalysis_dir=PosixPath('/lila/data/chodera/asap-datasets/mpro_fragalysis-04-01-24') structure_dir=None cache_dir='/lila/data/chodera/asap-datasets/mpro_fragalysis-04-01-24_curated_cache' use_only_cache=True save_to_cache=False target=<TargetTags.SARS-CoV-2-Mpro: 'SARS-CoV-2-Mpro'> write_final_sdf=True use_dask=True dask_type=<DaskType.LILAC_GPU: 'lilac-gpu'> dask_failure_mode=<DaskFailureMode.SKIP: 'skip'> dask_cluster_n_workers=10 dask_cluster_max_workers=200 n_select=5 logname='' loglevel='INFO' output_dir=PosixPath('/lila/data/chodera/asap-datasets/retro_docking/sars_fragalysis_retrospective/20240403_multi_pose_docking_self_docking') overwrite=True walltime='72h' structure_selector=<StructureSelector.SELF_DOCKING: 'SelfDockingSelector'> multi_reference=False relax=<POSIT_RELAX_MODE.NONE: 0> posit_method=<POSIT_METHOD.ALL: 15> use_omega=True omega_dense=False num_poses=50 allow_low_posit_prob=False low_posit_prob_thresh=0.1 allow_final_clash=False allow_retries=True
2024-04-10 10:52:37,580 | root | INFO | cross_docking.py | cross_docking_workflow | Dumping input schema to /lila/data/chodera/asap-datasets/retro_docking/sars_fragalysis_retrospective/20240403_multi_pose_docking_self_docking/inputs.json
2024-04-10 10:52:37,584 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | make_dask_client_meta | Using dask for parallelism of type: lilac-gpu
2024-04-10 10:52:37,585 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | dask_cluster_from_type | Platform: linux
2024-04-10 10:52:37,587 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | dask_cluster_from_type | Logical CPU count: 80
2024-04-10 10:52:37,591 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | dask_cluster_from_type | Physical CPU count: 40
2024-04-10 10:52:37,592 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | dask_cluster_from_type | Getting dask cluster of type lilac-gpu
2024-04-10 10:52:37,594 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | dask_cluster_from_type | Dask log level: INFO
2024-04-10 10:52:37,601 | dask_jobqueue.lsf | INFO | lsf.py | __init__ | ncpus specification for LSF not set, initializing it to 1
2024-04-10 10:52:37,602 | dask_jobqueue.lsf | INFO | lsf.py | __init__ | mem specification for LSF not set, initializing it to 96000000000 bytes
2024-04-10 10:52:41,657 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | make_dask_client_meta | Lilac HPC config selected, setting adaptive scaling
2024-04-10 10:52:41,663 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | make_dask_client_meta | Starting with minimum worker count: 10 workers
2024-04-10 10:52:41,668 | dask_jobqueue.lsf | INFO | lsf.py | __init__ | ncpus specification for LSF not set, initializing it to 1
2024-04-10 10:52:41,671 | dask_jobqueue.lsf | INFO | lsf.py | __init__ | mem specification for LSF not set, initializing it to 96000000000 bytes
2024-04-10 10:52:41,675 | dask_jobqueue.lsf | INFO | lsf.py | __init__ | ncpus specification for LSF not set, initializing it to 1
2024-04-10 10:52:41,677 | dask_jobqueue.lsf | INFO | lsf.py | __init__ | mem specification for LSF not set, initializing it to 96000000000 bytes
2024-04-10 10:52:41,679 | dask_jobqueue.lsf | INFO | lsf.py | __init__ | ncpus specification for LSF not set, initializing it to 1
2024-04-10 10:52:41,681 | dask_jobqueue.lsf | INFO | lsf.py | __init__ | mem specification for LSF not set, initializing it to 96000000000 bytes
2024-04-10 10:52:41,684 | asyncio | ERROR | base_events.py | default_exception_handler | Task exception was never retrieved
future: <Task finished name='Task-17' coro=<_wrap_awaitable() done, defined at /lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/distributed/deploy/spec.py:124> exception=TypeError('expected string or bytes-like object')>
Traceback (most recent call last):
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/distributed/deploy/spec.py", line 125, in _wrap_awaitable
    return await aw
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/distributed/deploy/spec.py", line 74, in _
    await self.start()
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/dask_jobqueue/core.py", line 427, in start
    self.job_id = self._job_id_from_submit_output(out)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/dask_jobqueue/core.py", line 433, in _job_id_from_submit_output
    match = re.search(self.job_id_regexp, out)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```
There's a bunch of these errors. And then I think it just stalls until LSF timeout.

**Comment by hmacdope** [comment]
Prefer `local` dask mode for now while I investigate.

**Comment by hmacdope** [comment]
@kaminow can you link your issue here also.

**Comment by kaminow** [comment]
@hmacdope I just ran a new docking run just to make sure I'm still getting the problem and I didn't mess anything up. output directory (including run script) is: `/data1/choderaj/kaminowb/structure_ml/docking_test` on `iris`.

the relevant stuff is in the run script:
```
#SBATCH -N 1
#SBATCH --partition=cpu
#SBATCH --mem=128GB
#SBATCH --cpus-per-task=16
```

and then in the log file, I get this:
```
2024-04-11 10:04:16,060 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | dask_cluster_from_type | Logical CPU count: 64
2024-04-11 10:04:16,062 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | dask_cluster_from_type | Physical CPU count: 64
2024-04-11 10:04:16,063 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | dask_cluster_from_type | Getting dask cluster of type local
2024-04-11 10:04:16,064 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | dask_cluster_from_type | Dask log level: INFO
2024-04-11 10:04:16,065 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | dask_cluster_from_type | initial guess 64 workers
2024-04-11 10:04:16,067 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | dask_cluster_from_type | Hyperthreading is disabled
2024-04-11 10:04:16,068 | asapdiscovery.data.util.dask_utils | INFO | dask_utils.py | dask_cluster_from_type | Executing with 64 workers
```

**Comment by hmacdope** [comment]
@apayne97 running some testing for you now, sorry for the slow reponse. Do you have a non-overwritten version of that folder?

@kaminow I think what might be happening is using `--cpus-per-task` without specifying `-ntasks` is selecting the full node `-N 1` .  Also running some tests now.

**Comment by hmacdope** [comment]
@kaminow ok ruling that out, It seems slurm is not hiding CPUs correctly from jobs, I will follow up with HPC, but in meantime we can force a specified config with command line flags which we will have to add.

**Comment by hmacdope** [comment]
Or you can just use a whole node, which is what is currently happening any
![Screenshot from 2024-04-22 13-50-59](https://github.com/choderalab/asapdiscovery/assets/24581003/5e48ec6c-8e32-48fa-b064-e95d74161d9f)
way 

Use port forwarding to have a look under the hood 

`ssh -o ServerAliveInterval=120 -A -L 8787:localhost:8787  iris -vvv  ssh -L 8787:127.0.0.1:8787 -N iscc003 -vvv` Have a look at the Notion guide for more info (won't link here).

**Comment by kaminow** [comment]
thanks so much for checking into this! seems like some annoying debugging
